"""
This is a Python module in the VisaFlow project.
"""

# Generated by Django 5.2.3 on 2025-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
