#!/usr/bin/env python
"""
Django’s command-line utility for administrative tasks.
Generated by default with each project.
"""

"""
Command-line utility for administrative tasks.
Generated by Django.
"""

import os
import sys

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'visa_tracker.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError("Couldn't import Django.") from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
